engines:
  fixme:
    enabled: true
  git-legal:
    enabled: true
  checkstyle:
    enabled: true
    config: 'config/checkstyle/checkstyle.xml'

ratings:
  paths:
    - "**.java"

exclude_paths:
- "test/"
- "**slang/**"
- "**/vendor/**"